public_html/protected/controllers/AuthController.php
<?php

/*
 * To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/

/**
 * Description of AuthController
 *
 * @author Cory
 */
class AuthController extends Controller {


	public $defaultAction = 'login';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
				'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules() {
		return array(
				array('allow',
						'actions'=>array('login'),
						'users'=>array('*'),
				),
				array('allow', // allow all users to perform 'index' and 'view' actions
						'users' => array('@'),
				),
				array('deny',  // deny all users
						'users'=>array('*'),
				),
		);
	}

	public function actionGenPass($password) {
		echo $password . "<br>";

		$hash = Helper::encrypting($password) . "<br>";
		echo $hash;
		echo Helper::decrypting($password, $hash) . "<br>";
	}

	/**
	 * Displays the login page
	 */
	public function actionLogin() {
		// If the user isn't logged in, show them the login page
		if (Yii::app()->user->isGuest) {

			$model = new LoginForm();
			// collect user input data
			if (isset($_POST['LoginForm'])) {
				$model->attributes = $_POST['LoginForm'];

				// validate user input and redirect to previous page if valid
				if ($model->validate()) {
					// Store their last visit time
					$this->lastVisit();
					// Return them to the return url if it's set.  Otherwise, go to their profile.
					$returnUrl = Yii::app()->user->returnUrl;
					if (strpos($returnUrl, 'index.php/') !== FALSE) {
						$this->redirect($returnUrl);
					} else {
						$this->redirect(Helper::$returnUrl);
					}
				} else {
					Yii::app()->user->setFlash('error', 'Some form items were not filled out correctly.');
				}
			}
			// display the login form
			$this->render('login', array('model' => $model));
		} else {
			$this->redirect(Yii::app()->user->returnUrl);
		}
	}

	public function actionLogout() {
		Yii::app()->user->logout();
		$this->redirect(Helper::$returnLogoutUrl);
	}



	private function lastVisit() {
		$lastVisit = User::model()->findByPk(Yii::app()->user->id);
		$lastVisit->lastvisit_at = date('Y-m-d H:i:s');
		$lastVisit->save();
	}

}

public_html/protected/controllers/PostController.php
<?php

class PostController extends Controller
{
	public $layout='column2';

	/**
	 * @var CActiveRecord the currently loaded data model instance.
	 */
	private $_model;

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
				'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
				array('allow',  // allow all users to access 'index' and 'view' actions.
						'actions'=>array('index','view'),
						'users'=>array('*'),
				),
				array('allow', // allow authenticated users to access all actions
						'users'=>array('@'),
				),
				array('deny',  // deny all users
						'users'=>array('*'),
				),
		);
	}

	/**
	 * Displays a particular model.
	 */
	public function actionView()
	{


		$post=$this->loadModel();
		$comment=$this->newComment($post);

		$this->render('view',array(
				'model'=>$post,
				'comment'=>$comment,
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Post;
		if(isset($_POST['Post']))
		{
			$model->attributes=$_POST['Post'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('create',array(
				'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionUpdate()
	{
		$model=$this->loadModel();
		if(isset($_POST['Post']))
		{
			$model->attributes=$_POST['Post'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
				'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'index' page.
	 */
	public function actionDelete()
	{
		if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			$this->loadModel()->delete();

			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if(!isset($_GET['ajax']))
				$this->redirect(array('index'));
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$criteria=new CDbCriteria(array(
				'condition'=>'status='.Post::STATUS_PUBLISHED,
				'order'=>'update_time DESC',
				'with'=>'commentCount',
		));
		if(isset($_GET['tag']))
			$criteria->addSearchCondition('tags',$_GET['tag']);

		$dataProvider=new CActiveDataProvider('Post', array(
				'pagination'=>array(
						'pageSize'=>Yii::app()->params['postsPerPage'],
				),
				'criteria'=>$criteria,
		));

		$this->render('index',array(
				'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Post('search');
		if(isset($_GET['Post']))
			$model->attributes=$_GET['Post'];
		$this->render('admin',array(
				'model'=>$model,
		));
	}

	/**
	 * Suggests tags based on the current user input.
	 * This is called via AJAX when the user is entering the tags input.
	 */
	public function actionSuggestTags()
	{
		if(isset($_GET['q']) && ($keyword=trim($_GET['q']))!=='')
		{
			$tags=Tag::model()->suggestTags($keyword);
			if($tags!==array())
				echo implode("\n",$tags);
		}
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 */
	public function loadModel()
	{
		if($this->_model===null)
		{
			if(isset($_GET['id']))
			{
				if(Yii::app()->user->isGuest)
					$condition='status='.Post::STATUS_PUBLISHED.' OR status='.Post::STATUS_ARCHIVED;
				else
					$condition='';
				$this->_model=Post::model()->findByPk($_GET['id'], $condition);
			}
			if($this->_model===null)
				throw new CHttpException(404,'The requested page does not exist.');
		}
		return $this->_model;
	}

	/**
	 * Creates a new comment.
	 * This method attempts to create a new comment based on the user input.
	 * If the comment is successfully created, the browser will be redirected
	 * to show the created comment.
	 * @param Post the post that the new comment belongs to
	 * @return Comment the comment instance
	 */
	protected function newComment($post)
	{
		$comment=new Comment;
		if(isset($_POST['ajax']) && $_POST['ajax']==='comment-form')
		{
			echo CActiveForm::validate($comment);
			Yii::app()->end();
		}
		if(isset($_POST['Comment']))
		{
				
			$user = Yii::app()->getComponent('user');
			$comment->attributes=$_POST['Comment'];
			if($post->addComment($comment))
			{
				if($comment->status==Comment::STATUS_PENDING) {
					Yii::app()->user->setFlash('commentSubmitted','Thank you for your comment. Your comment will be posted once it is approved.');
					$user->setFlash(
							'success',
							'<strong>Success</strong> your comment has been submitted and is awaiting approval'
					);
				}
				$this->refresh();
			} else
			{
				$user->setFlash(
						'danger',
						'<strong>Failure</strong> your comment failed to submit.'
				);
				$this->refresh();
					
			}

		}
		return $comment;
	}
}

public_html/protected/views/layouts/column1.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div id="content">
	<?php echo $content; ?>
</div><!-- content -->
<?php $this->endContent(); ?>

public_html/protected/views/layouts/column2.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div class="container">
	<div class="row">
		<div class="col-sm-9">

			<?php echo $content; ?>
		</div>
		<div class="col-sm-3">
			<br>
			<?php if(!Yii::app()->user->isGuest) $this->widget('AdminMenu'); ?>

			<?php $this->widget('TagCloud', array(
					'maxTags'=>Yii::app()->params['tagCloudCount'],
  			  )); ?>
			<?php $this->widget('UserMenu'); ?>
		</div>
	</div>
</div>
<!-- content -->
<?php $this->endContent(); ?>

public_html/protected/views/layouts/main.php
<?php 
// Get client script
$cs=Yii::app()->clientScript;
$baseUrl = Yii::app()->baseUrl;

// Add CSS
$cs->registerCSSFile($baseUrl.'/css/main.css');

// Add Jquery
$cs->registerCoreScript('jquery');

// Add lightGallery
$cs->registerCSSFile($baseUrl.'/jquery/lightGallery/css/lightGallery.css');
$cs->registerScriptFile($baseUrl.'/jquery/lightGallery/js/lightGallery.min.js');

// Add Jquery share
$cs->registerCSSFile($baseUrl.'/jquery/share/jquery.share.css');
$cs->registerScriptFile($baseUrl.'/jquery/share/jquery.share.js');


// Add Syntax Highlighter
$cs->registerCssFile($baseUrl.'/jquery/syntaxHighlighter/styles/shCore.css');
$cs->registerCssFile($baseUrl.'/jquery/syntaxHighlighter/styles/shThemeDefault.css');
$cs->registerScriptFile($baseUrl.'/jquery/syntaxHighlighter/scripts/shCore.js');
$cs->registerScriptFile($baseUrl.'/jquery/syntaxHighlighter/scripts/shAutoloader.js');

?>

<?php /* @var $this Controller */ ?>
<!DOCTYPE html>
<html lang="en">
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="language" content="en" />

<title><?php echo CHtml::encode($this->pageTitle); ?></title>
</head>



<?php $this->widget('booster.widgets.TbNavbar', array(
		'brand' => 'LHG',
		'brandOptions' => array('style' => 'width:auto;margin-left: 0px;'),
		'fixed' => 'top',
		'fluid' => false,
		'collapse' => true,
		'items' => array(
				array(
						'class' => 'booster.widgets.TbMenu',
						'type' => 'navbar',
						'items' => array(
								array('label' => 'Wobble Rocket', 'url' => array('site/wobbleRocket')),
								array('label' => 'Ant Simulator', 'url' => array('site/antSimulator')),
								array('label' => 'Dev Blog & Tutorials', 'url' => array('post/index')),
								array('label' => 'About', 'url'=>array('site/page', 'view'=>'about')),
								array('label' => 'Contact', 'url'=> array('site/contact')),
								array('label' => 'Logout', 'url'=>array('auth/logout'), 'visible'=>!Yii::app()->user->isGuest)
						),
				),
		),
)); ?>



<body>
	<?php echo $content; ?>
	<div id="share"></div>
</body>
<script type="text/javascript">

	
	$( document ).ready(function() {
		function path()
      {
        var args = arguments,
            result = []
            ;
             
        for(var i = 0; i < args.length; i++)
            result.push(args[i].replace('@', '<?php echo $baseUrl;?>/jquery/syntaxHighlighter/scripts/'));
             
        return result
      };
	       
	      SyntaxHighlighter.autoloader.apply(null, path(
	        'applescript            @shBrushAppleScript.js',
	        'actionscript3 as3      @shBrushAS3.js',
	        'bash shell             @shBrushBash.js',
	        'coldfusion cf          @shBrushColdFusion.js',
	        'cpp c                  @shBrushCpp.js',
	        'c# c-sharp csharp      @shBrushCSharp.js',
	        'css                    @shBrushCss.js',
	        'delphi pascal          @shBrushDelphi.js',
	        'diff patch pas         @shBrushDiff.js',
	        'erl erlang             @shBrushErlang.js',
	        'groovy                 @shBrushGroovy.js',
	        'java                   @shBrushJava.js',
	        'jfx javafx             @shBrushJavaFX.js',
	        'js jscript javascript  @shBrushJScript.js',
	        'perl pl                @shBrushPerl.js',
	        'php                    @shBrushPhp.js',
	        'text plain             @shBrushPlain.js',
	        'py python              @shBrushPython.js',
	        'ruby rails ror rb      @shBrushRuby.js',
	        'sass scss              @shBrushSass.js',
	        'scala                  @shBrushScala.js',
	        'sql                    @shBrushSql.js',
	        'vb vbnet               @shBrushVb.js',
	        'xml xhtml xslt html    @shBrushXml.js'
	    ));
		SyntaxHighlighter.all();
		
		$("#lightGallery").lightGallery({speed:200,});
		    	   
		$('#share').share({
			networks: ['twitter','facebook','tumblr','pinterest','googleplus'],
			orientation: 'vertical',
			urlToShare: 'http://www.lasthackergames.com',
			affix: 'right center'
		});
	});

    	    
    	 
</script>
</html>