public_html/protected/models/Comment.php
<?php

class Comment extends CActiveRecord
{
	/**
	 * The followings are the available columns in table 'tbl_comment':
	 * @var integer $id
	 * @var string $content
	 * @var integer $status
	 * @var integer $create_time
	 * @var string $author
	 * @var string $email
	 * @var string $url
	 * @var integer $post_id
	 */
	const STATUS_PENDING=1;
	const STATUS_APPROVED=2;

	/**
	 * Returns the static model of the specified AR class.
	 * @return CActiveRecord the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return '{{comment}}';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('content, author, email', 'required'),
			array('author, email, url', 'length', 'max'=>128),
			array('email','email'),
			array('url','url'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'post' => array(self::BELONGS_TO, 'Post', 'post_id'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'Id',
			'content' => 'Comment',
			'status' => 'Status',
			'create_time' => 'Create Time',
			'author' => 'Name',
			'email' => 'Email',
			'url' => 'Website',
			'post_id' => 'Post',
		);
	}

	/**
	 * Approves a comment.
	 */
	public function approve()
	{
		$this->status=Comment::STATUS_APPROVED;
		$this->update(array('status'));
	}

	/**
	 * @param Post the post that this comment belongs to. If null, the method
	 * will query for the post.
	 * @return string the permalink URL for this comment
	 */
	public function getUrl($post=null)
	{
		if($post===null)
			$post=$this->post;
		return $post->url.'#c'.$this->id;
	}

	/**
	 * @return string the hyperlink display for the current comment's author
	 */
	public function getAuthorLink()
	{
		if(!empty($this->url))
			return CHtml::link(CHtml::encode($this->author),$this->url);
		else
			return CHtml::encode($this->author);
	}

	/**
	 * @return integer the number of comments that are pending approval
	 */
	public function getPendingCommentCount()
	{
		return $this->count('status='.self::STATUS_PENDING);
	}

	/**
	 * @param integer the maximum number of comments that should be returned
	 * @return array the most recently added comments
	 */
	public function findRecentComments($limit=10)
	{
		return $this->with('post')->findAll(array(
			'condition'=>'t.status='.self::STATUS_APPROVED,
			'order'=>'t.create_time DESC',
			'limit'=>$limit,
		));
	}

	/**
	 * This is invoked before the record is saved.
	 * @return boolean whether the record should be saved.
	 */
	protected function beforeSave()
	{
		if(parent::beforeSave())
		{
			if($this->isNewRecord)
				$this->create_time=time();
			return true;
		}
		else
			return false;
	}
}

public_html/protected/models/Post.php
<?php

class Post extends CActiveRecord
{
	/**
	 * The followings are the available columns in table 'tbl_post':
	 * @var integer $id
	 * @var string $title
	 * @var string $content
	 * @var string $tags
	 * @var string summary
	 * @var string thumb_url
	 * @var integer $status
	 * @var integer $create_time
	 * @var integer $update_time
	 * @var integer $author_id
	 */
	const STATUS_DRAFT=1;
	const STATUS_PUBLISHED=2;
	const STATUS_ARCHIVED=3;

	private $_oldTags;

	/**
	 * Returns the static model of the specified AR class.
	 * @return CActiveRecord the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return '{{post}}';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
				array('title, content, summary, thumb_url, status', 'required'),
				array('status', 'in', 'range'=>array(1,2,3)),
				array('title', 'length', 'max'=>128),
				array('summary', 'length', 'max'=>500),
				array('thumb_url', 'length', 'max'=>256),
				array('tags', 'match', 'pattern'=>'/^[\w\s,]+$/', 'message'=>'Tags can only contain word characters.'),
				array('tags', 'normalizeTags'),

				array('title, status', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
				'author' => array(self::BELONGS_TO, 'User', 'author_id'),
				'comments' => array(self::HAS_MANY, 'Comment', 'post_id', 'condition'=>'comments.status='.Comment::STATUS_APPROVED, 'order'=>'comments.create_time DESC'),
				'commentCount' => array(self::STAT, 'Comment', 'post_id', 'condition'=>'status='.Comment::STATUS_APPROVED),
		);
	}

	/**
	 * @param integer the maximum number of comments that should be returned
	 * @return array the most recently added comments
	 */
	public function findRecentPosts($limit=5)
	{
		return $this->findAll(array(
				'condition'=>'t.status='.self::STATUS_PUBLISHED,
				'order'=>'t.create_time DESC',
				'limit'=>$limit,
		));
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
				'id' => 'Id',
				'title' => 'Title',
				'content' => 'Content',
				'tags' => 'Tags',
				'status' => 'Status',
				'create_time' => 'Create Time',
				'update_time' => 'Update Time',
				'author_id' => 'Author',
		);
	}

	/**
	 * @return string the URL that shows the detail of the post
	 */
	public function getUrl()
	{
		return Yii::app()->createUrl('post/view', array(
				'id'=>$this->id,
				'title'=>$this->title,
		));
	}

	/**
	 * @return array a list of links that point to the post list filtered by every tag of this post
	 */
	public function getTagLinks()
	{
		$links=array();
		foreach(Tag::string2array($this->tags) as $tag)
			$links[]=CHtml::link(CHtml::encode($tag), array('post/index', 'tag'=>$tag));
		return $links;
	}
	
	public function getTags()
	{
		$links=array();
		foreach(Tag::string2array($this->tags) as $tag)
			$links[CHtml::encode($tag)] = array('post/index', 'tag'=>$tag);
		return $links;
	}

	/**
	 * Normalizes the user-entered tags.
	 */
	public function normalizeTags($attribute,$params)
	{
		$this->tags=Tag::array2string(array_unique(Tag::string2array($this->tags)));
	}

	/**
	 * Adds a new comment to this post.
	 * This method will set status and post_id of the comment accordingly.
	 * @param Comment the comment to be added
	 * @return boolean whether the comment is saved successfully
	 */
	public function addComment($comment)
	{
		if(Yii::app()->params['commentNeedApproval'])
			$comment->status=Comment::STATUS_PENDING;
		else
			$comment->status=Comment::STATUS_APPROVED;
		$comment->post_id=$this->id;
		return $comment->save();
	}

	/**
	 * This is invoked when a record is populated with data from a find() call.
	 */
	protected function afterFind()
	{
		parent::afterFind();
		$this->_oldTags=$this->tags;
	}

	/**
	 * This is invoked before the record is saved.
	 * @return boolean whether the record should be saved.
	 */
	protected function beforeSave()
	{
		if(parent::beforeSave())
		{
			if($this->isNewRecord)
			{
				$this->create_time=$this->update_time=time();
				$this->author_id=Yii::app()->user->id;
			}
			else
				$this->update_time=time();
			return true;
		}
		else
			return false;
	}

	/**
	 * This is invoked after the record is saved.
	 */
	protected function afterSave()
	{
		parent::afterSave();
		Tag::model()->updateFrequency($this->_oldTags, $this->tags);
	}

	/**
	 * This is invoked after the record is deleted.
	 */
	protected function afterDelete()
	{
		parent::afterDelete();
		Comment::model()->deleteAll('post_id='.$this->id);
		Tag::model()->updateFrequency($this->tags, '');
	}

	/**
	 * Retrieves the list of posts based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the needed posts.
	 */
	public function search()
	{
		$criteria=new CDbCriteria;

		$criteria->compare('title',$this->title,true);

		$criteria->compare('status',$this->status);

		return new CActiveDataProvider('Post', array(
				'criteria'=>$criteria,
				'sort'=>array(
						'defaultOrder'=>'status, update_time DESC',
				),
		));
	}
	
	public function scopes()
	{
		return array(
				'published'=>array(
						'condition'=>'status='.self::STATUS_PUBLISHED,
				),
				'recently'=>array(
						'order'=>'create_time DESC',
						'limit'=>10,
				),
		);
	}
}

public_html/protected/controllers/PostController.php
<?php

class PostController extends Controller
{
	public $layout='column2';

	/**
	 * @var CActiveRecord the currently loaded data model instance.
	 */
	private $_model;

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
				'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
				array('allow',  // allow all users to access 'index' and 'view' actions.
						'actions'=>array('index','view'),
						'users'=>array('*'),
				),
				array('allow', // allow authenticated users to access all actions
						'users'=>array('@'),
				),
				array('deny',  // deny all users
						'users'=>array('*'),
				),
		);
	}

	/**
	 * Displays a particular model.
	 */
	public function actionView()
	{


		$post=$this->loadModel();
		$comment=$this->newComment($post);

		$this->render('view',array(
				'model'=>$post,
				'comment'=>$comment,
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Post;
		if(isset($_POST['Post']))
		{
			$model->attributes=$_POST['Post'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('create',array(
				'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionUpdate()
	{
		$model=$this->loadModel();
		if(isset($_POST['Post']))
		{
			$model->attributes=$_POST['Post'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
				'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'index' page.
	 */
	public function actionDelete()
	{
		if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			$this->loadModel()->delete();

			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if(!isset($_GET['ajax']))
				$this->redirect(array('index'));
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$criteria=new CDbCriteria(array(
				'condition'=>'status='.Post::STATUS_PUBLISHED,
				'order'=>'update_time DESC',
				'with'=>'commentCount',
		));
		if(isset($_GET['tag']))
			$criteria->addSearchCondition('tags',$_GET['tag']);

		$dataProvider=new CActiveDataProvider('Post', array(
				'pagination'=>array(
						'pageSize'=>Yii::app()->params['postsPerPage'],
				),
				'criteria'=>$criteria,
		));

		$this->render('index',array(
				'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Post('search');
		if(isset($_GET['Post']))
			$model->attributes=$_GET['Post'];
		$this->render('admin',array(
				'model'=>$model,
		));
	}

	/**
	 * Suggests tags based on the current user input.
	 * This is called via AJAX when the user is entering the tags input.
	 */
	public function actionSuggestTags()
	{
		if(isset($_GET['q']) && ($keyword=trim($_GET['q']))!=='')
		{
			$tags=Tag::model()->suggestTags($keyword);
			if($tags!==array())
				echo implode("\n",$tags);
		}
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 */
	public function loadModel()
	{
		if($this->_model===null)
		{
			if(isset($_GET['id']))
			{
				if(Yii::app()->user->isGuest)
					$condition='status='.Post::STATUS_PUBLISHED.' OR status='.Post::STATUS_ARCHIVED;
				else
					$condition='';
				$this->_model=Post::model()->findByPk($_GET['id'], $condition);
			}
			if($this->_model===null)
				throw new CHttpException(404,'The requested page does not exist.');
		}
		return $this->_model;
	}

	/**
	 * Creates a new comment.
	 * This method attempts to create a new comment based on the user input.
	 * If the comment is successfully created, the browser will be redirected
	 * to show the created comment.
	 * @param Post the post that the new comment belongs to
	 * @return Comment the comment instance
	 */
	protected function newComment($post)
	{
		$comment=new Comment;
		if(isset($_POST['ajax']) && $_POST['ajax']==='comment-form')
		{
			echo CActiveForm::validate($comment);
			Yii::app()->end();
		}
		if(isset($_POST['Comment']))
		{
				
			$user = Yii::app()->getComponent('user');
			$comment->attributes=$_POST['Comment'];
			if($post->addComment($comment))
			{
				if($comment->status==Comment::STATUS_PENDING) {
					Yii::app()->user->setFlash('commentSubmitted','Thank you for your comment. Your comment will be posted once it is approved.');
					$user->setFlash(
							'success',
							'<strong>Success</strong> your comment has been submitted and is awaiting approval'
					);
				}
				$this->refresh();
			} else
			{
				$user->setFlash(
						'danger',
						'<strong>Failure</strong> your comment failed to submit.'
				);
				$this->refresh();
					
			}

		}
		return $comment;
	}
}

public_html/protected/views/post/_comments.php
<?php foreach($comments as $comment): ?>
<div class="comment" id="c<?php echo $comment->id; ?>">
	<div class="author">
		<strong><?php echo $comment->authorLink; ?> </strong> says:
	</div>
	<div class="time">
		<?php echo date('F j, Y \a\t h:i a',$comment->create_time); ?>
	</div>

	<div class="content">
		<?php echo nl2br(CHtml::encode($comment->content)); ?>
	</div>

</div>
<!-- comment -->
<?php endforeach; ?>

public_html/protected/views/post/_form.php
<?php
/* @var $this PostController */
/* @var $model Post */
/* @var $form TbActiveForm */
?>
<script>
	function openKCFinder_singleFile() {
	    window.KCFinder = {};
	    window.KCFinder.callBack = function(url) {
	        // Actions with url parameter here
	        window.KCFinder = null;
	        $('#thumbUrl').val(url);
	    };
	    window.open('<?php echo Yii::app()->baseUrl . '/vendor/kcfinder/browse.php?type=images'; ?>');
	};
	
	 $(document).ready(
			 function() {
				 $('#getUrl').click(function() {
					openKCFinder_singleFile();
					//alert('getting url');
				});
			});
</script>
<div class="form">
	<?php $form=$this->beginWidget('booster.widgets.TbActiveForm', array(
			'id'=>'post-form',
			// Please note: When you enable ajax validation, make sure the corresponding
			// controller action is handling ajax validation correctly.
			// There is a call to performAjaxValidation() commented in generated controller code.
			// See class documentation of CActiveForm for details on this.
			'enableAjaxValidation'=>false,
)); ?>

	<p class="help-block">
		Fields with <span class="required">*</span> are required.
	</p>

	<?php echo $form->errorSummary($model); ?>

	<?php echo $form->textFieldGroup($model,'title',array('span'=>5,'maxlength'=>128)); ?>

	<?php echo $form->textAreaGroup($model, 'summary',array('rows'=>6,'span'=>6)); ?>
	
	<?php 
	echo '<div class="form-group">';
	echo $form->label($model,'thumb_url', array('required'=>true));
	echo '<div class="input-group">';
	echo $form->textField(
			$model,
			'thumb_url',
			array(
					'id'=>'thumbUrl',
					'class'=>'form-control'
			)
	);
	echo '<div class="input-group-btn">';
	$this->widget(
			'booster.widgets.TbButton',
			array(
					'label' => 'Set File',
					'id'=> 'getUrl',
			)
	);
	echo '</div>';
	echo '</div>';
	echo '</div>';
	?>

	<?php echo $form->ckEditorGroup(
			$model,
			'content',
			array(
					'wrapperHtmlOptions' => array(
							/* 'class' => 'col-sm-5', */
					),
					'widgetOptions' => array(
							'editorOptions' => array(
									'filebrowserImageBrowseUrl'=> Yii::app()->baseUrl . '/vendor/kcfinder/browse.php?type=images',
									'fullpage' => 'js:true',
									/* 'width' => '640', */
									/* 'resize_maxWidth' => '640', */
									/* 'resize_minWidth' => '320'*/
							)
					)
			)
); ?>
	<?php 
	/*
	 echo $form->redactorGroup(
	 		$model,
	 		'content',
	 		array(
	 				'widgetOptions' => array(
	 						'editorOptions' => array(
	 								'fileUpload' => $this->createUrl('site/testFileUpload'),
	 								'imageUpload' => $this->createUrl('site/testImageUpload'),
	 								//									'imageGetJson'=> $this->createUrl('site/testImageThumbs'),
	 								'width'=>'100%',
	 								'height'=>'400px',
	 								'options' => array('color' => true)
	 						),
	 				),

	 		)
			); */?>


	<?php echo $form->textAreaGroup($model,'tags',array('rows'=>6,'span'=>6)); ?>


	<?php echo $form->dropDownListGroup(
			$model,
			'status',
			array(
					'wrapperHtmlOptions' => array(
							'class' => 'col-sm-5',
					),
					'widgetOptions' => array(
							'data' => Lookup::items('PostStatus'),
							'htmlOptions' => array('multiple' => false),
					)
			)
); ?>

	<?php $this->widget(
			'booster.widgets.TbButton',
			array('buttonType' => 'reset', 'label' => 'Reset')
		); ?>
	<?php $this->widget( 'booster.widgets.TbButton',array(
			'buttonType' =>	'submit',
			'context' => 'primary',
			'label' => $model->isNewRecord ? 'Create' : 'Save')
			);?>

	<?php $this->endWidget(); ?>

</div>
<!-- form -->

public_html/protected/views/post/_search.php
<?php
/* @var $this PostController */
/* @var $model Post */
/* @var $form CActiveForm */
?>

<div class="wide form">

	<?php $form=$this->beginWidget('booster.widgets.TbActiveForm', array(
			'action'=>Yii::app()->createUrl($this->route),
			'method'=>'get',
)); ?>

	<?php echo $form->textFieldGroup($model,'id',array('span'=>5)); ?>

	<?php echo $form->textFieldGroup($model,'title',array('span'=>5,'maxlength'=>128)); ?>

	<?php echo $form->textAreaGroup($model,'content',array('rows'=>6,'span'=>8)); ?>

	<?php echo $form->textAreaGroup($model,'tags',array('rows'=>6,'span'=>8)); ?>

	<?php echo $form->textFieldGroup($model,'status',array('span'=>5)); ?>

	<?php echo $form->textFieldGroup($model,'create_time',array('span'=>5)); ?>

	<?php echo $form->textFieldGroup($model,'update_time',array('span'=>5)); ?>

	<?php echo $form->textFieldGroup($model,'author_id',array('span'=>5)); ?>

	<div class="form-actions">
		<?php $this->widget( 'booster.widgets.TbButton',array(
				'buttonType' =>	'submit',
				'context' => 'primary',
				'label' => 'Search')
			);?>
	</div>

	<?php $this->endWidget(); ?>

</div>
<!-- search-form -->

public_html/protected/views/post/_view.php
<?php
/* @var $this PostController */
/* @var $data Post */
?>

<div class="post">
	<div class="title">
		<h1>
			<?php echo CHtml::link(CHtml::encode(CHtml::encode($data->title)),$data->url);  ?>
		</h1>
		<?php // Render them all with single `TbAlert`
$this->widget('booster.widgets.TbAlert', array(
		'fade' => true,
		'closeText' => '&times;', // false equals no close link
		'userComponentId' => 'user',
		'alerts' => array( // configurations per alert type
				'success','danger', // you don't need to specify full config
		),
		));?>

	</div>
	<div class="author">
		<strong> posted by <?php echo $data->author->username . ' on ' . date('F j, Y',$data->create_time); ?>
		</strong>
	</div>


	<?php
	$this->beginWidget('CMarkdown', array('purifyOutput'=>true));
	echo $data->content;
	$this->endWidget();
	?>

	<div class="nav">
		<b>Tags:</b>
		<?php echo implode(', ', $data->tagLinks); ?>
		<br />
		<?php echo CHtml::link('Permalink', $data->url); ?>
		|
		<?php echo CHtml::link("Comments ({$data->commentCount})",$data->url.'#comments'); ?>
		| Last updated on
		<?php echo date('F j, Y',$data->update_time); ?>
	</div>


</div>

public_html/protected/views/post/admin.php
<?php
/* @var $this PostController */
/* @var $model Post */
$this->pageTitle= Yii::app()->name . ' - ' . Yii::t('app','Manage Posts');
Yii::app()->clientScript->registerScript('search', "
		$('.search-form form').submit(function(){
		$('#post-grid').yiiGridView('update', {
		data: $(this).serialize()
});
		return false;
});
		");
?>

<h1>Manage Posts</h1>

<p>
	You may optionally enter a comparison operator (<b>&lt;</b>, <b>&lt;=</b>,
	<b>&gt;</b>, <b>&gt;=</b>, <b> &lt;&gt;</b> or <b>=</b>) at the
	beginning of each of your search values to specify how the comparison
	should be done.
</p>

Advanced Search:
<?php $this->widget(
		'booster.widgets.TbSwitch',
		array(
				'name' => 'testToggleButton',

				'events' => array(
						'switchChange' => 'js:function($el, status, e){$(\'.search-form\').toggle();}'
				),
				'options' => array(
						'size' => 'small', //null, 'mini', 'small', 'normal', 'large
				),
		)
    );?>
<div class="search-form" style="display: none">
	<?php $this->renderPartial('_search',array(
			'model'=>$model,
)); ?>
</div>
<!-- search-form -->

<?php $this->widget('booster.widgets.TbExtendedGridView',array(
		'id'=>'post-grid',
		'fixedHeader' => true,
		'headerOffset' => 40,
		'type' => 'striped',
		'dataProvider'=>$model->search(),
		'filter'=>$model,
		'template' => "{items}",
		'responsiveTable' => true,
		'columns'=>array(
				'id',
				'title',
				array(
						'name'=>'content',
						'value' => 'CHtml::encode(Helper::truncateText($data->content,Yii::app()->params[\'truncationLength\']));',
				),
					
				'tags',
				'status',
				array(
						'name'=>'create_time',
						'value' => 'Yii::app()->format->date($data->create_time);',
				),
				array(
						'name'=>'update_time',
						'value' => 'Yii::app()->format->date($data->update_time);',
				),

				array(
						'htmlOptions' => array('nowrap'=>'nowrap'),
						'class'=>'booster.widgets.TbButtonColumn',
						'template'=>'{view}{update}{delete}',
				),
				/*
				 'author_id',
*/

		),
)); ?>

public_html/protected/views/post/create.php
<?php
/* @var $this PostController */
/* @var $model Post */
$this->pageTitle= Yii::app()->name . ' - ' . Yii::t('app','Create Post');
?>

<h1>Create Post</h1>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

public_html/protected/views/post/index.php
<?php
/* @var $this PostController */
/* @var $dataProvider CActiveDataProvider */
$this->pageTitle=$this->pageTitle= Yii::app()->name . ' - ' . 'Dev Blog & Tutorials';
?>

<?php if(!empty($_GET['tag'])): ?>
<h1>
	Posts Tagged with <em>'<?php echo CHtml::encode($_GET['tag']); ?>'
	</em>
</h1>
<?php endif; ?>

<?php $this->widget('booster.widgets.TbListView',array(
		'dataProvider'=>$dataProvider,
		'itemView'=>'_view',
		'template'=>"{items}\n{pager}",
));  ?>

public_html/protected/views/post/update.php
<?php
/* @var $this PostController */
/* @var $model Post */
$this->pageTitle= Yii::app()->name . ' - ' . Yii::t('app',$model->title);
?>

<h1>
	Update Post
	<?php echo $model->id; ?>
</h1>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

public_html/protected/views/post/view.php
<?php
$this->pageTitle= Yii::app()->name . ' - ' . Yii::t('app',$model->title);
?>

<?php $this->renderPartial('_view', array(
		'data'=>$model,
)); ?>

<div id="comments">
	<?php if($model->commentCount>=1): ?>
	<h3>
		<?php echo $model->commentCount>1 ? $model->commentCount . ' comments' : 'One comment'; ?>
	</h3>

	<?php $this->renderPartial('_comments',array(
			'post'=>$model,
			'comments'=>$model->comments,
		)); ?>
	<?php endif; ?>

	<h3>Leave a Comment</h3>
	<?php if(Yii::app()->user->hasFlash('commentSubmitted')): ?>
	<div class="flash-success">
		<?php echo Yii::app()->user->getFlash('commentSubmitted'); ?>
	</div>
	<?php else: ?>
	<?php $this->renderPartial('/comment/_form',array(
			'model'=>$comment,
		)); ?>
	<?php endif; ?>
</div>